// <auto-generated />
using System;
using AirlineTicketingSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineTicketingSystem.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260117041038_AddUniquePassport")]
    partial class AddUniquePassport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirlineTicketingSystem.Models.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Country");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Iata_Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Airport_Name");

                    b.HasKey("Id");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Karachi",
                            Country = "Pakistan",
                            IataCode = "KHI",
                            Name = "Jinnah Intl"
                        },
                        new
                        {
                            Id = 2,
                            City = "Lahore",
                            Country = "Pakistan",
                            IataCode = "LHE",
                            Name = "Allama Iqbal Intl"
                        },
                        new
                        {
                            Id = 3,
                            City = "Islamabad",
                            Country = "Pakistan",
                            IataCode = "ISB",
                            Name = "Islamabad Intl"
                        },
                        new
                        {
                            Id = 4,
                            City = "Dubai",
                            Country = "UAE",
                            IataCode = "DXB",
                            Name = "Dubai Intl"
                        },
                        new
                        {
                            Id = 5,
                            City = "Abu Dhabi",
                            Country = "UAE",
                            IataCode = "AUH",
                            Name = "Zayed Intl"
                        },
                        new
                        {
                            Id = 6,
                            City = "Jeddah",
                            Country = "Saudi Arabia",
                            IataCode = "JED",
                            Name = "King Abdulaziz"
                        },
                        new
                        {
                            Id = 7,
                            City = "Riyadh",
                            Country = "Saudi Arabia",
                            IataCode = "RUH",
                            Name = "King Khalid"
                        },
                        new
                        {
                            Id = 8,
                            City = "London",
                            Country = "UK",
                            IataCode = "LHR",
                            Name = "Heathrow"
                        },
                        new
                        {
                            Id = 9,
                            City = "New York",
                            Country = "USA",
                            IataCode = "JFK",
                            Name = "JFK Intl"
                        },
                        new
                        {
                            Id = 10,
                            City = "Doha",
                            Country = "Qatar",
                            IataCode = "DOH",
                            Name = "Hamad Intl"
                        },
                        new
                        {
                            Id = 11,
                            City = "Faisalabad",
                            Country = "Pakistan",
                            IataCode = "LYP",
                            Name = "Faisalabad Intl"
                        },
                        new
                        {
                            Id = 12,
                            City = "Multan",
                            Country = "Pakistan",
                            IataCode = "MUX",
                            Name = "Multan Intl"
                        },
                        new
                        {
                            Id = 13,
                            City = "Quetta",
                            Country = "Pakistan",
                            IataCode = "UET",
                            Name = "Quetta Intl"
                        },
                        new
                        {
                            Id = 14,
                            City = "Sialkot",
                            Country = "Pakistan",
                            IataCode = "SKT",
                            Name = "Sialkot Intl"
                        },
                        new
                        {
                            Id = 15,
                            City = "Skardu",
                            Country = "Pakistan",
                            IataCode = "KDU",
                            Name = "Skardu Airport"
                        },
                        new
                        {
                            Id = 16,
                            City = "Mumbai",
                            Country = "India",
                            IataCode = "BOM",
                            Name = "Chhatrapati Shivaji"
                        },
                        new
                        {
                            Id = 17,
                            City = "Delhi",
                            Country = "India",
                            IataCode = "DEL",
                            Name = "Indira Gandhi Intl"
                        },
                        new
                        {
                            Id = 18,
                            City = "Bangalore",
                            Country = "India",
                            IataCode = "BLR",
                            Name = "Kempegowda Intl"
                        },
                        new
                        {
                            Id = 19,
                            City = "Chennai",
                            Country = "India",
                            IataCode = "MAA",
                            Name = "Chennai Intl"
                        },
                        new
                        {
                            Id = 20,
                            City = "Hyderabad",
                            Country = "India",
                            IataCode = "HYD",
                            Name = "Rajiv Gandhi Intl"
                        },
                        new
                        {
                            Id = 21,
                            City = "Singapore",
                            Country = "Singapore",
                            IataCode = "SIN",
                            Name = "Changi Airport"
                        },
                        new
                        {
                            Id = 22,
                            City = "Tokyo",
                            Country = "Japan",
                            IataCode = "HND",
                            Name = "Haneda Airport"
                        },
                        new
                        {
                            Id = 23,
                            City = "Tokyo",
                            Country = "Japan",
                            IataCode = "NRT",
                            Name = "Narita Intl"
                        },
                        new
                        {
                            Id = 24,
                            City = "Beijing",
                            Country = "China",
                            IataCode = "PEK",
                            Name = "Capital Intl"
                        },
                        new
                        {
                            Id = 25,
                            City = "Shanghai",
                            Country = "China",
                            IataCode = "PVG",
                            Name = "Pudong Intl"
                        },
                        new
                        {
                            Id = 26,
                            City = "Hong Kong",
                            Country = "China",
                            IataCode = "HKG",
                            Name = "Hong Kong Intl"
                        },
                        new
                        {
                            Id = 27,
                            City = "Seoul",
                            Country = "South Korea",
                            IataCode = "ICN",
                            Name = "Incheon Intl"
                        },
                        new
                        {
                            Id = 28,
                            City = "Bangkok",
                            Country = "Thailand",
                            IataCode = "BKK",
                            Name = "Suvarnabhumi Airport"
                        },
                        new
                        {
                            Id = 29,
                            City = "Kuala Lumpur",
                            Country = "Malaysia",
                            IataCode = "KUL",
                            Name = "Kuala Lumpur Intl"
                        },
                        new
                        {
                            Id = 30,
                            City = "Istanbul",
                            Country = "Turkey",
                            IataCode = "IST",
                            Name = "Istanbul Airport"
                        },
                        new
                        {
                            Id = 31,
                            City = "Paris",
                            Country = "France",
                            IataCode = "CDG",
                            Name = "Charles de Gaulle"
                        },
                        new
                        {
                            Id = 32,
                            City = "Frankfurt",
                            Country = "Germany",
                            IataCode = "FRA",
                            Name = "Frankfurt Airport"
                        },
                        new
                        {
                            Id = 33,
                            City = "Munich",
                            Country = "Germany",
                            IataCode = "MUC",
                            Name = "Munich Airport"
                        },
                        new
                        {
                            Id = 34,
                            City = "Amsterdam",
                            Country = "Netherlands",
                            IataCode = "AMS",
                            Name = "Schiphol Airport"
                        },
                        new
                        {
                            Id = 35,
                            City = "Madrid",
                            Country = "Spain",
                            IataCode = "MAD",
                            Name = "Adolfo Suárez"
                        },
                        new
                        {
                            Id = 36,
                            City = "Barcelona",
                            Country = "Spain",
                            IataCode = "BCN",
                            Name = "El Prat Airport"
                        },
                        new
                        {
                            Id = 37,
                            City = "Rome",
                            Country = "Italy",
                            IataCode = "FCO",
                            Name = "Fiumicino Airport"
                        },
                        new
                        {
                            Id = 38,
                            City = "Zurich",
                            Country = "Switzerland",
                            IataCode = "ZRH",
                            Name = "Zurich Airport"
                        },
                        new
                        {
                            Id = 39,
                            City = "Moscow",
                            Country = "Russia",
                            IataCode = "SVO",
                            Name = "Sheremetyevo Intl"
                        },
                        new
                        {
                            Id = 40,
                            City = "London",
                            Country = "UK",
                            IataCode = "LGW",
                            Name = "Gatwick Airport"
                        },
                        new
                        {
                            Id = 41,
                            City = "Manchester",
                            Country = "UK",
                            IataCode = "MAN",
                            Name = "Manchester Airport"
                        },
                        new
                        {
                            Id = 42,
                            City = "Birmingham",
                            Country = "UK",
                            IataCode = "BHX",
                            Name = "Birmingham Airport"
                        },
                        new
                        {
                            Id = 43,
                            City = "Los Angeles",
                            Country = "USA",
                            IataCode = "LAX",
                            Name = "LAX Intl"
                        },
                        new
                        {
                            Id = 44,
                            City = "Chicago",
                            Country = "USA",
                            IataCode = "ORD",
                            Name = "O'Hare Intl"
                        },
                        new
                        {
                            Id = 45,
                            City = "Dallas",
                            Country = "USA",
                            IataCode = "DFW",
                            Name = "Dallas/Fort Worth"
                        },
                        new
                        {
                            Id = 46,
                            City = "Atlanta",
                            Country = "USA",
                            IataCode = "ATL",
                            Name = "Hartsfield-Jackson"
                        },
                        new
                        {
                            Id = 47,
                            City = "San Francisco",
                            Country = "USA",
                            IataCode = "SFO",
                            Name = "SFO Intl"
                        },
                        new
                        {
                            Id = 48,
                            City = "Miami",
                            Country = "USA",
                            IataCode = "MIA",
                            Name = "Miami Intl"
                        },
                        new
                        {
                            Id = 49,
                            City = "Toronto",
                            Country = "Canada",
                            IataCode = "YYZ",
                            Name = "Pearson Intl"
                        },
                        new
                        {
                            Id = 50,
                            City = "Vancouver",
                            Country = "Canada",
                            IataCode = "YVR",
                            Name = "Vancouver Intl"
                        },
                        new
                        {
                            Id = 51,
                            City = "Sydney",
                            Country = "Australia",
                            IataCode = "SYD",
                            Name = "Kingsford Smith"
                        },
                        new
                        {
                            Id = 52,
                            City = "Melbourne",
                            Country = "Australia",
                            IataCode = "MEL",
                            Name = "Melbourne Airport"
                        },
                        new
                        {
                            Id = 53,
                            City = "Auckland",
                            Country = "New Zealand",
                            IataCode = "AKL",
                            Name = "Auckland Airport"
                        },
                        new
                        {
                            Id = 54,
                            City = "Johannesburg",
                            Country = "South Africa",
                            IataCode = "JNB",
                            Name = "OR Tambo Intl"
                        },
                        new
                        {
                            Id = 55,
                            City = "Cairo",
                            Country = "Egypt",
                            IataCode = "CAI",
                            Name = "Cairo Intl"
                        },
                        new
                        {
                            Id = 56,
                            City = "Muscat",
                            Country = "Oman",
                            IataCode = "MCT",
                            Name = "Muscat Intl"
                        },
                        new
                        {
                            Id = 57,
                            City = "Kuwait City",
                            Country = "Kuwait",
                            IataCode = "KWI",
                            Name = "Kuwait Intl"
                        },
                        new
                        {
                            Id = 58,
                            City = "Manama",
                            Country = "Bahrain",
                            IataCode = "BAH",
                            Name = "Bahrain Intl"
                        },
                        new
                        {
                            Id = 59,
                            City = "Tehran",
                            Country = "Iran",
                            IataCode = "IKA",
                            Name = "Imam Khomeini Intl"
                        },
                        new
                        {
                            Id = 60,
                            City = "Colombo",
                            Country = "Sri Lanka",
                            IataCode = "CMB",
                            Name = "Bandaranaike Intl"
                        },
                        new
                        {
                            Id = 61,
                            City = "Dhaka",
                            Country = "Bangladesh",
                            IataCode = "DAC",
                            Name = "Hazrat Shahjalal"
                        },
                        new
                        {
                            Id = 62,
                            City = "Kathmandu",
                            Country = "Nepal",
                            IataCode = "KTM",
                            Name = "Tribhuvan Intl"
                        },
                        new
                        {
                            Id = 63,
                            City = "Male",
                            Country = "Maldives",
                            IataCode = "MLE",
                            Name = "Velana Intl"
                        },
                        new
                        {
                            Id = 64,
                            City = "Jakarta",
                            Country = "Indonesia",
                            IataCode = "CGK",
                            Name = "Soekarno-Hatta"
                        },
                        new
                        {
                            Id = 65,
                            City = "Manila",
                            Country = "Philippines",
                            IataCode = "MNL",
                            Name = "Ninoy Aquino Intl"
                        },
                        new
                        {
                            Id = 66,
                            City = "Ho Chi Minh",
                            Country = "Vietnam",
                            IataCode = "SGN",
                            Name = "Tan Son Nhat"
                        },
                        new
                        {
                            Id = 67,
                            City = "Taipei",
                            Country = "Taiwan",
                            IataCode = "TPE",
                            Name = "Taoyuan Intl"
                        },
                        new
                        {
                            Id = 68,
                            City = "Lisbon",
                            Country = "Portugal",
                            IataCode = "LIS",
                            Name = "Humberto Delgado"
                        },
                        new
                        {
                            Id = 69,
                            City = "Stockholm",
                            Country = "Sweden",
                            IataCode = "ARN",
                            Name = "Arlanda Airport"
                        },
                        new
                        {
                            Id = 70,
                            City = "Oslo",
                            Country = "Norway",
                            IataCode = "OSL",
                            Name = "Oslo Airport"
                        },
                        new
                        {
                            Id = 71,
                            City = "Copenhagen",
                            Country = "Denmark",
                            IataCode = "CPH",
                            Name = "Copenhagen Airport"
                        },
                        new
                        {
                            Id = 72,
                            City = "Helsinki",
                            Country = "Finland",
                            IataCode = "HEL",
                            Name = "Helsinki Airport"
                        },
                        new
                        {
                            Id = 73,
                            City = "Vienna",
                            Country = "Austria",
                            IataCode = "VIE",
                            Name = "Vienna Intl"
                        },
                        new
                        {
                            Id = 74,
                            City = "Brussels",
                            Country = "Belgium",
                            IataCode = "BRU",
                            Name = "Brussels Airport"
                        },
                        new
                        {
                            Id = 75,
                            City = "Athens",
                            Country = "Greece",
                            IataCode = "ATH",
                            Name = "Athens Intl"
                        },
                        new
                        {
                            Id = 76,
                            City = "Prague",
                            Country = "Czech Republic",
                            IataCode = "PRG",
                            Name = "Václav Havel"
                        },
                        new
                        {
                            Id = 77,
                            City = "Warsaw",
                            Country = "Poland",
                            IataCode = "WAW",
                            Name = "Chopin Airport"
                        },
                        new
                        {
                            Id = 78,
                            City = "Dublin",
                            Country = "Ireland",
                            IataCode = "DUB",
                            Name = "Dublin Airport"
                        },
                        new
                        {
                            Id = 79,
                            City = "Edinburgh",
                            Country = "UK",
                            IataCode = "EDI",
                            Name = "Edinburgh Airport"
                        },
                        new
                        {
                            Id = 80,
                            City = "Boston",
                            Country = "USA",
                            IataCode = "BOS",
                            Name = "Logan Intl"
                        },
                        new
                        {
                            Id = 81,
                            City = "Washington",
                            Country = "USA",
                            IataCode = "IAD",
                            Name = "Dulles Intl"
                        },
                        new
                        {
                            Id = 82,
                            City = "Houston",
                            Country = "USA",
                            IataCode = "IAH",
                            Name = "George Bush Intl"
                        },
                        new
                        {
                            Id = 83,
                            City = "Seattle",
                            Country = "USA",
                            IataCode = "SEA",
                            Name = "Seattle-Tacoma"
                        },
                        new
                        {
                            Id = 84,
                            City = "Denver",
                            Country = "USA",
                            IataCode = "DEN",
                            Name = "Denver Intl"
                        },
                        new
                        {
                            Id = 85,
                            City = "Las Vegas",
                            Country = "USA",
                            IataCode = "LAS",
                            Name = "Harry Reid Intl"
                        },
                        new
                        {
                            Id = 86,
                            City = "Mexico City",
                            Country = "Mexico",
                            IataCode = "MEX",
                            Name = "Benito Juárez"
                        },
                        new
                        {
                            Id = 87,
                            City = "Sao Paulo",
                            Country = "Brazil",
                            IataCode = "GRU",
                            Name = "Guarulhos Intl"
                        },
                        new
                        {
                            Id = 88,
                            City = "Buenos Aires",
                            Country = "Argentina",
                            IataCode = "EZE",
                            Name = "Ministro Pistarini"
                        },
                        new
                        {
                            Id = 89,
                            City = "Santiago",
                            Country = "Chile",
                            IataCode = "SCL",
                            Name = "Arturo Merino"
                        },
                        new
                        {
                            Id = 90,
                            City = "Lima",
                            Country = "Peru",
                            IataCode = "LIM",
                            Name = "Jorge Chávez"
                        },
                        new
                        {
                            Id = 91,
                            City = "Bogota",
                            Country = "Colombia",
                            IataCode = "BOG",
                            Name = "El Dorado Intl"
                        },
                        new
                        {
                            Id = 92,
                            City = "Nairobi",
                            Country = "Kenya",
                            IataCode = "NBO",
                            Name = "Jomo Kenyatta"
                        },
                        new
                        {
                            Id = 93,
                            City = "Casablanca",
                            Country = "Morocco",
                            IataCode = "CMN",
                            Name = "Mohammed V"
                        },
                        new
                        {
                            Id = 94,
                            City = "Addis Ababa",
                            Country = "Ethiopia",
                            IataCode = "ADD",
                            Name = "Bole Intl"
                        },
                        new
                        {
                            Id = 95,
                            City = "Cape Town",
                            Country = "South Africa",
                            IataCode = "CPT",
                            Name = "Cape Town Intl"
                        },
                        new
                        {
                            Id = 96,
                            City = "Tel Aviv",
                            Country = "Israel",
                            IataCode = "TLV",
                            Name = "Ben Gurion"
                        },
                        new
                        {
                            Id = 97,
                            City = "Amman",
                            Country = "Jordan",
                            IataCode = "AMM",
                            Name = "Queen Alia Intl"
                        },
                        new
                        {
                            Id = 98,
                            City = "Beirut",
                            Country = "Lebanon",
                            IataCode = "BEY",
                            Name = "Rafic Hariri"
                        },
                        new
                        {
                            Id = 99,
                            City = "Baghdad",
                            Country = "Iraq",
                            IataCode = "BGW",
                            Name = "Baghdad Intl"
                        },
                        new
                        {
                            Id = 100,
                            City = "Perth",
                            Country = "Australia",
                            IataCode = "PER",
                            Name = "Perth Airport"
                        });
                });

            modelBuilder.Entity("AirlineTicketingSystem.Models.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("BookingDate");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BookingReference");

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("FlightId");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit")
                        .HasColumnName("IsPaid");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("PassengerId");

                    b.Property<int>("PassengerType")
                        .HasColumnType("int")
                        .HasColumnName("PassengerType");

                    b.Property<int>("SeatClass")
                        .HasColumnType("int")
                        .HasColumnName("SeatClass");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int")
                        .HasColumnName("SeatCount");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("AirlineTicketingSystem.Models.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailableBusinessSeats")
                        .HasColumnType("int");

                    b.Property<int>("AvailableEconomySeats")
                        .HasColumnType("int");

                    b.Property<int>("AvailableFirstClassSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("BusinessPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BusinessSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("EconomyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EconomySeats")
                        .HasColumnType("int");

                    b.Property<decimal>("FirstClassPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FirstClassSeats")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FromAirport")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelayed")
                        .HasColumnType("bit");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ToAirport")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("AirlineTicketingSystem.Models.Entities.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ContactEmail");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("First_Name");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Last_Name");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nationality");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PassportNumber");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PassportNumber")
                        .IsUnique();

                    b.HasIndex("PassportNumber", "UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("AirlineTicketingSystem.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hashed_password");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AirlineTicketingSystem.Models.Entities.Booking", b =>
                {
                    b.HasOne("AirlineTicketingSystem.Models.Entities.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirlineTicketingSystem.Models.Entities.Passenger", "Passenger")
                        .WithMany("Bookings")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("AirlineTicketingSystem.Models.Entities.Flight", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("AirlineTicketingSystem.Models.Entities.Passenger", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
